spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: smart
    password: sjl123456
    url: jdbc:mysql://39.108.183.2/smart?characterEncoding=utf-8&useSSL=false&&serverTimezone=GMT%2b8&zeroDateTimeBehavior=convertToNull
  jpa:
    show-sql: true
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
  jackson:
    time-zone: GMT+8